name: Java release CI with Gradle

on:
  push:
    branches: [ "release/**" ]
  pull_request:
    branches: [ "release/**" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: print env
        run: echo "${{ secrets.APPLICATION_RELEASE_ENV }}"

      - name: Make application.yml executable
        run: |
          mkdir ./src/main/resources
          cd ./src/main/resources
      #        touch ./application.yml
      #        touch ./application-dev.yml
      #        chmod +x src/main/resources/application.yml
      #        chmod +x src/main/resources/application-dev.yml

      - name: Copy Secret
        env:
          OCCUPY_SECRETS: ${{ secrets.APPLICATION_RELEASE_ENV }}
          OCCUPY_PROD_SECRETS: ${{ secrets.APPLICATION_RELEASE_PROD_ENV }}
          OCCUPY_SECRET_DIR: src/main/resources
          OCCUPY_SECRET_FILE: application.yml
          OCCUPY_SECRET_PROD_FILE: application-prod.yml
        run: |
          echo $OCCUPY_SECRETS | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_FILE &&
          echo $OCCUPY_PROD_SECRETS | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_PROD_FILE &&
          find src

      - name: Check if the file exists
        run:
          ls -l ./src/main/resources
        shell: bash

      - name: Check if the file is a regular file
        run: file ./src/main/resources/application-prod.yml
        shell: bash

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew |
          chmod +x src/main/resources

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        #      uses: ./gradlew build
        with:
          arguments: build